site_name: Tennis Knowledge Base
site_url: https://tenniskb.github.io/tnkb/

theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: green
      accent: light green
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.path
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - awesome-pages

extra_css:
  - stylesheets/extra.css

extra:
  alternate:
    - name: English
      link: /tnkb/
      lang: en
    - name: Tiếng Việt
      link: /tnkb/vi/
      lang: vi

docs_dir: docs
